overwrite: true
generates: # 파일 생성 경로
  src/graphql/GeneralBackend/generated.tsx:
    schema: # schema : GraphQL Schema 소스를 어디서 가져올 것인지를 설정하는 옵션. 여기선 직접 서버와 통신하는 url 주소를 넣음. (만약 클라이언트와 서버 소스를 모노레포로 관리하고 있다면 파일 경로를 직접 지정해줄 수 있음)
      - 'https://sesacthon-server.lucas-gong.dev/graphql' # 백엔드에서 제공되는 GraphQL API endpoint
    documents: 'graphql/GeneralBackend/**/*.graphql' # documents : gql 태그를 사용해서 쿼리 언어를 작성하거나 .graphql 파일 내에 작성해 둔 쿼리 언어를 Document로 변환할 수 있도록 파일 경로를 지정한 옵션
    plugins: # plugins : 타입으로 변환할 때 사용할 플러그인들을 명시할 수 있는 옵션
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
  graphql/generated.tsx:
    schema:
      - 'https://sesacthon-server.lucas-gong.dev/graphql'
    documents: 'graphql/GeneralBackend/**/*.graphql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
